version: '3'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - OVPN_NETWORK=${OVPN_NETWORK}
      - OVPN_SUBNET=${OVPN_SUBNET}
      - OVPN_PROTO=${OVPN_PROTO}
      - OVPN_DNS=${OVPN_DNS}
    volumes:
      - ovpn-data:/etc/openvpn
    restart: always

  pritunl:
    image: pritunl/pritunl-zero
    container_name: pritunl
    ports:
      - "443:443"
    depends_on:
      - openvpn
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ID=${NODE_ID}
      - SERVER_PORT=80
      - SERVER_PROTOCOL=http
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ALLOW_INSECURE=true
    volumes:
      - pritunl-data:/data
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
      - MONGO_USER=${USERNAME}
      - MONGO_PASS=${PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always

volumes:
  ovpn-data:
  pritunl-data:
  mongodb-data:
