version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST}

      # Optional:
      - PASSWORD=${PASSWORD}
      - WG_PORT=51820
      #- WG_DEFAULT_ADDRESS=10.8.0.1/24
      # - WG_DEFAULT_DNS=1.1.1.1

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "85:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  noip:
    image: aanousakis/no-ip:latest
    environment:
      USERNAME_FILE: /run/secrets/username
      PASSWORD_FILE: /run/secrets/password
      DOMAINS_FILE:  /run/secrets/domains
      INTERVAL_FILE: /run/secrets/interval
    secrets:
      - username
      - password
      - domains
      - interval
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
 username:
   external: true
 password:
   external: true
 domains:
   external: true 
 interval:
   external: true
