version: "3.8"
services:
  clouddns:
    build:
      context: ./clouddns
      dockerfile: Dockerfile
    environment:
      DYNAMIC_DNS_URL: ${DYNAMIC_DNS_URL}
      HOSTNAME: ${HOSTNAME}
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${HOSTNAME}

      # Optional:
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - PUID=1000
      - PGID=1000
      - TZ=America/Mendoza
      - SERVERURL=${HOSTNAME} #optional
      - PEERS=${PEERS} #optional
      - PEERDNS=auto #optional

    image: weejewel/wg-easy:latest
    #image: ghcr.io/weejewel/wg-easy:latest
    #container_name: wg-easy
    volumes:
      - ./etc/wireguard:/etc/wireguard
    ports:
      - ${WG_PORT}:51820/udp
      - ${WG_PORT_WEB}:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
